import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import LoginModal from '@/components/LoginModal'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [session, setSession] = useState(false)
  return (
    <>
      <Head>
        <title>Home page</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        {session ? null : <LoginModal></LoginModal>}
      </main>
      {/* <LoginModal session={session}></LoginModal> */}
    </>
  )
}
//not login
function Guest() {
  return (
    <main className="container mx-auto text-center py-20">
      <h3 className="text-4xl font-bold">Guest Homepage</h3>
    </main>
  )
}
//Authorize